# -*- coding: utf-8 -*-
"""DeptApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5fQtdWERRpG7sjyd-1SBSbHm6E2Kaao
"""

import streamlit as st
import tensorflow as tf

@st.cache(allow_output_mutation=True)


def load_model():
  model=tf.keras.models.load_model('model_weather.h5')
  return model

model=load_model()

types = {0: 'Cloudy', 1: 'Rain', 2: 'Shine', 3: 'Sunrise'}

st.write("""
# Multi-Weather Classification Deep Learning Model"""
)

file=st.file_uploader("Take a picture of the sky above and upload it here! Do note that only jpg and png files are accepted. Thank you!",type=["jpg","png"])


import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(64,64)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names= types
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)
